### ISSUE TITLE
Bad release names

### ISSUE THREAD

**Issue by def-** [yugabyte/yugabyte-db-thirdparty#110]
[v20220413154237-81bb2d6459-almalinux8-aarch64-13](https://github.com/yugabyte/yugabyte-db-thirdparty/releases/tag/v20220413154237-81bb2d6459-almalinux8-aarch64-13)
[v20220413110343-81bb2d6459-almalinux8-aarch64-14](https://github.com/yugabyte/yugabyte-db-thirdparty/releases/tag/v20220413110343-81bb2d6459-almalinux8-aarch64-14)
[v20220413061606-81bb2d6459-almalinux8-aarch64-12](https://github.com/yugabyte/yugabyte-db-thirdparty/releases/tag/v20220413061606-81bb2d6459-almalinux8-aarch64-12)
There should be a clang before the 13/14/12.
They fail with `build-support/thirdparty_tool -u`:
```
Traceback (most recent call last):
  File "/Users/deen/code/yugabyte-db/python/yb/thirdparty_tool.py", line 637, in <module>
    main()
  File "/Users/deen/code/yugabyte-db/python/yb/thirdparty_tool.py", line 582, in main
    updater.update_archive_metadata_file()
  File "/Users/deen/code/yugabyte-db/python/yb/thirdparty_tool.py", line 384, in update_archive_metadata_file
    yb_dep_release = GitHubThirdPartyRelease(release)
  File "/Users/deen/code/yugabyte-db/python/yb/thirdparty_tool.py", line 142, in __init__
    raise ValueError(f"Could not parse tag: {tag}, does not match regex: {TAG_RE}")
ValueError: Could not parse tag: v20220413154237-81bb2d6459-almalinux8-aarch64-13, does not match regex: re.compile('^v(?:(?P<branch_name>[0-9.]+)-)?(?P<timestamp>[0-9]+)-(?P<sha_prefix>[0-9a-f]+)(?:-(?P<architecture1>x86_64|aarch64|arm64))?(?:-(?P<os>(?:macos|almalinux|alpine|centos|debian|fedora|ol|rocky|ubuntu|o)
```
I can try removing them. They are currently not used on yugabyte-db master branch
CC @spolitov

**Comment by def-** [comment]
Seems to have worked.
